node:
    id: node-2
    raftPort: 9092
    httpPort: 8082
    dataDir: ./data/node-2

cluster:
    nodes:
        - id: node-1
          raftAddress: localhost:9091
          httpAddress: http://localhost:8081
        - id: node-2
          raftAddress: localhost:9092
          httpAddress: http://localhost:8082
        - id: node-3
          raftAddress: localhost:9093
          httpAddress: http://localhost:8083

    electionTimeoutMin: 1500
    electionTimeoutMax: 3000
    heartbeatInterval: 500

http:
    maxRequestSize: 1048576
    requestTimeout: 5000
    connectionPoolSize: 10
