node:
  id: node1
  raftPort: 9001
  httpPort: 8081
  dataDir: data/node1

cluster:
  nodes:
    - id: node1
      raftAddress: localhost:9001
      httpAddress: localhost:8081
    - id: node2
      raftAddress: localhost:9002
      httpAddress: localhost:8082
    - id: node3
      raftAddress: localhost:9003
      httpAddress: localhost:8083
